apiVersion: v2
name: server
description: A Helm chart for the Woodpecker server
type: application
version: 2.0.0
# renovate: datasource=github-releases depName=woodpecker-ci/woodpecker extractVersion=^v(?<version>.*)$
appVersion: 2.8.0
home: https://woodpecker-ci.org/
icon: https://avatars.githubusercontent.com/u/84780935?s=200&v=4

keywords:
  - continuous-delivery
  - continuous-deployment
  - continuous-integration
  - docker
  - go
  - kubernetes

sources:
  - https://github.com/woodpecker-ci/woodpecker.git

maintainers:
  - name: Woodpecker Maintainers
    email: owner@woodpecker-ci.org
    url: https://github.com/woodpecker-ci
