apiVersion: v2
name: agent
description: A Helm chart for the Woodpecker agent
type: application
version: 0.1.1
appVersion: "v0.15.8"
home: https://woodpecker-ci.org/
icon: https://avatars.githubusercontent.com/u/84780935?s=200&v=4

keywords:
  - continuous-delivery
  - continuous-deployment
  - continuous-integration
  - docker
  - go
  - kubernetes

sources:
  - https://github.com/woodpecker-ci/woodpecker.git

maintainers:
  - name: Woodpecker Maintainers
    email: owner@woodpecker-ci.org
    url: https://github.com/woodpecker-ci
